method: "VectorPainter"

image_size: 1024
path_svg: ~
fix_scale: False # if the target image is not squared, it is recommended to fix the scale

# train
imit_stage: # brushstroke imitation
  num_iter: 250
  lr: 1
  color_lr: 0.01
  width_lr: 0.1
  lr_scheduler: False
  decay_steps: [ 100, 200 ]

synth_stage: # synthesis with style supervision
  num_iter: 2000
  lr: 1
  color_lr: 0.01
  width_lr: 0.1
  lr_scheduler: False
  decay_steps: [ 1000, 1500 ]

batch_size: 1 # TODO: support batch size

# position loss weight
pos_type: 'sinkhorn' # 'pos', 'bez', 'sinkhorn'
pos_loss_weight: 1.0
struct_loss: "ssim" # "ssim", "msssim"
struct_loss_weight: 0.1
l2_loss: 0.9

# stroke attrs
random_init: False
num_paths: 5000 # number of strokes
width: 1.5 # init stroke width
max_width: 50 # max stroke width
control_points_per_seg: 3 # Number of points to sample per parametrized curve.
num_segments: 1
optim_opacity: True # if True, the stroke opacity is optimized
optim_width: True # if True, the stroke width is optimized
optim_rgba: True # if True, the stroke RGBA is optimized
color_vars_threshold: 0.0 # uncomment the code

# diffusion
model_id: "sdxl" # sd14, sd15, sd21, sd21b, sdxl
torch_compile: True
SDPA: True
enable_xformers: False
gradient_checkpoint: False
cpu_offload: True
num_inference_steps: 50
guidance_scale: 10.0
