#-----------------#
#  Global Config  #
#-----------------#

# prompt
style: ~ # style file path
style_prompt: ~
prompt: ~
neg_prompt: ~ # negative prompt

# canvas size
canvas_w: 1024 # canvas_width
canvas_h: 1024 # canvas_height

# accelerate config
state:
  cpu: False # use cpu
  mprec: no # mixed precision, choices: 'no', 'fp16', 'bf16'

# diffusers config
diffuser:
  download: False # Set this variable to True the first time it runs
  force_download: False
  resume_download: False

# PyDiffVG config
diffvg:
  print_timing: False

# reproduction
seed: 951222
# multi-run
multirun: False
srange: ~ # seed range, example: [100, 100]

# log
result_path: './workspace'
save_step: 50

# visual rendering process
mv: True # make video
framefreq: 50 # save the image interval
framerate: 24 # by adjusting the frame rate, you can control the playback speed of the output video

# hydra setting
hydra:
  help:
    # app name, override to match the name your app is known by
    app_name: 'VectorPainter'
  run:
    # output directory for normal runs
    # warning: make sure that the L53-55 of './libs/utils/model_state.py' and 'dir' are modified together
    dir: ./${result_path}/${x.method}-${now:%Y-%m-%d-%H-%M}

# default settings
defaults:
  - _self_
  - x: ~
  - override hydra/job_logging: disabled # Outputs only to stdout (no log file)